name = "Pszygoda"
author = "FFTV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index-1.14.79.toml"
hash-format = "sha256"
hash = "f881f7b1a293e55757540d4afd4a999320e1b4ffe043e8337f0b0b31ee9d6a98"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
