name = "Pszygoda"
author = "FFTV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfb898f6474d951e5af2a518820efdabd5585f737ec398f22b12e0e3af7dbb08"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
