name = "Pszygoda"
author = "FFTV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45cd6733f54ae525d3495d738efc6f51a9f4d6be5355cfc2dd7a89584ac79481"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
